### ISSUE TITLE
YOLO2COCO

### ISSUE THREAD

**Issue by hewumars** [ISSResearch/Dataset-Converters#2]
have plan?

**Comment by ArutyunovG** [comment]
Hi @hewumars 

At the moment we are concentrated on developing a new repo, Dataset-Converters is on support. 
If you are interested in new converter it is always welcome to contribute a pr! YOLOs are cool single-stage detection models, so we'll approve and maintain your changes.

**Comment by ArMaxik** [comment]
Hello, @hewumars

We've added `YOLO2COCO` and `COCO2YOLO` converters. Hope, they will help you :)
