### ISSUE TITLE
Multiclass input training set Pascal VOC

### ISSUE THREAD

**Issue by apiszcz** [ISSResearch/Dataset-Converters#3]
I have multiple class annotations created in VoTT exported to Pascal VOC.
I would like to convert these into COCO format.

When I attempt conversion 
python convert.py --input-folder PascalVOC-export --output-folder coco --input-format VOC --output-format COCO

FileNotFoundError: [Errno 2] No such file or directory: PascalVOC-export\\ImageSets\\Main\\train.txt'

Each class has its own train.txt (e.g. dog_train.txt, dog_val.txt, cat_train.txt, cat_val.txt)... there is not a single file train.txt for all classes.

Is there a better approach to converting VoTT annotation to COCO?

**Comment by ArutyunovG** [comment]
Conversion from Pascal VOC works only for the original VOC datasets. There is no conversion implemented starting from VoTT.
